apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
        - name: movie-service
          image: yourdockeruser/movie-service:latest
          command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              value: "postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev"
            - name: CAST_SERVICE_HOST_URL
              value: "http://movie-service:8000/api/v1/movie/"